name: C/C++ CI
image: mxklb/docker-qt5-deb

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: qmake
      run: qmake LilSing.pro -r CONFIG+=debug
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
