name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev qtmultimedia5-dev libqt5multimediawidgets5
    - name: wherarewe
      run: pwd
    - name: qmake
      run: qmake LilSing/LilSing.pro -r CONFIG+=debug -o result
    - run: ls -la
    - run: cat .makefile
    - name: make
      run: make
    - name: make check
      run: make check
