name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: linter
      run: pip install cpplint && cpplint --recursive --filter=-build/include_subdir ./
    - run: sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev qtmultimedia5-dev libqt5multimediawidgets5
    - name: qmake
      run: qmake Karaoke.pro -r CONFIG+=debug
    - name: make
      run: make
    - name: make check
      run: make check
    
