name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev qtmultimedia5-dev libqt5multimediawidgets5
    - name: qmake
      run: cd LilSing && qmake LilSing.pro -r CONFIG+=debug
    - name: make
      run: cd LilSing && make
    - name: make check
      run: cd LilSing cat Makefile && make check
